# Generated by Django 3.1.7 on 2021-02-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupTitle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RatedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='')),
                ('itemGroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kcs_choice.itemgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingOrder', models.TextField()),
                ('itemGroup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kcs_choice.itemgroup')),
            ],
        ),
    ]
