# Generated by Django 3.1.7 on 2021-02-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kcs_choice', '0002_auto_20210220_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentrating',
            name='itemGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kcs_choice.itemgroup'),
        ),
    ]
