# Generated by Django 3.1.7 on 2021-02-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcs_choice', '0003_auto_20210220_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemgroup',
            name='groupDescrip',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rateditem',
            name='datafield_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rateditem',
            name='datafield_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rateditem',
            name='datafield_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rateditem',
            name='datafield_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rateditem',
            name='datafield_5',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
